models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title Заголовок
 * @property string $description Описание
 * @property string $text Текст
 * @property int $categoryId Категория
 * @property string $image Изображение
 * @property string $createdAt Дата создания
 *
 * @property Image[] $images
 * @property Category $category
 */
class News extends \yii\db\ActiveRecord
{
	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return 'news';
	}

	/**
	 * {@inheritdoc}
	 */
	public function rules()
	{
		return [
			[['title', 'text'], 'required'],
			[['description', 'text'], 'string'],
			[['categoryId'], 'integer'],
			[['createdAt'], 'safe'],
			[['title'], 'string', 'max' => 255],
			[['image'], 'string', 'max' => 256]];
	}

	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'title' => 'Заголовок',
			'description' => 'Описание',
			'text' => 'Текст',
			'categoryId' => 'Категория',
			'image' => 'Изображение',
			'createdAt' => 'Дата создания',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getImages()
	{
		return $this->hasMany(Image::className(), ['newsId' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getCategory()
	{
		return $this->hasOne(Category::className(), ['id' => 'categoryId']);
	}
}

controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\News;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class NewsController extends Controller
{
	public function actions()
	{
		$path = 'uploads/' . date('Y/m/d');
		FileHelper::createDirectory($path);

		return [
			'image-upload' => [
				'class' => 'vova07\imperavi\actions\UploadFileAction',
				'url' => '/' . $path, // Directory URL address, where files are stored.
				'path' => $path, // Or absolute path to directory where files are stored.
			],
		];
	}


	public function actionIndex()
	{
		$models = News::find()->all();

		return $this->render('index', [
			'models' => $models
		]);
	}

	/**
	 * @param $id
	 * @return string
	 * @throws NotFoundHttpException
	 */
	public function actionUpdate($id)
	{
		$model = News::findOne(['id' => $id]);

		if ($model === null) {
			throw new NotFoundHttpException('Новость не найдена.');
		}

		if ($model->load(\Yii::$app->request->post()) && $model->save()) {
			\Yii::$app->session->setFlash('success');
			return $this->refresh();
		}

		return $this->render('update', [
			'model' => $model
		]);
	}

	public function actionFileUpload()
	{

	}
}

views/news/index.php
<?php

/* @var $models \app\models\News[] */

?>

<h1>Новости</h1>

<?php foreach ($models as $model): ?>

	<article>
		<h3><?= $model->title ?></h3>
		<p><?= $model->description ?></p>

		<?php if (!Yii::$app->user->isGuest): ?>

			<div>
				<?= \yii\helpers\Html::a('Редактировать', ['news/update', 'id' => $model->id]) ?>
			</div>

		<?php endif; ?>
	</article>

<?php endforeach; ?>

views/news/update.php
<?php

/* @var $this \yii\web\View */
/* @var $model \app\models\News */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Изменить новость №' . $model->id;
?>

<h1><?= $this->title ?></h1>

<?php if (Yii::$app->session->hasFlash('success')): ?>

	<p class="alert alert-success">Всё успешно сохранено !</p>

<?php endif; ?>

<?php $form = \yii\widgets\ActiveForm::begin() ?>

	<?= $form->field($model, 'title')->textInput() ?>

	<?= $form->field($model, 'description')->widget(\vova07\imperavi\Widget::class, [
		'settings' => [
			'lang' => 'ru',
			'minHeight' => 200,
			'imageUpload' => Url::to(['/news/image-upload']),
		]
	]) ?>

	<?= $form->field($model, 'active')->checkbox() ?>

	<div class="form-group">
		<?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
	</div>

<?php \yii\widgets\ActiveForm::end() ?>